// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmROI(arg1) {
  return window['go']['main']['App']['ConfirmROI'](arg1);
}

export function ConfirmSnip(arg1) {
  return window['go']['main']['App']['ConfirmSnip'](arg1);
}

export function EnterFrameMode() {
  return window['go']['main']['App']['EnterFrameMode']();
}

export function ExitFrameMode() {
  return window['go']['main']['App']['ExitFrameMode']();
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function GetCapturedCount() {
  return window['go']['main']['App']['GetCapturedCount']();
}

export function GetDisplayData() {
  return window['go']['main']['App']['GetDisplayData']();
}

export function GetMirrorData() {
  return window['go']['main']['App']['GetMirrorData']();
}

export function GetSnipData() {
  return window['go']['main']['App']['GetSnipData']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SelectArea() {
  return window['go']['main']['App']['SelectArea']();
}

export function SetROI(arg1) {
  return window['go']['main']['App']['SetROI'](arg1);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
