// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmROI(arg1:main.ROI):Promise<void>;

export function ConfirmSnip(arg1:main.ROI):Promise<void>;

export function EnterFrameMode():Promise<void>;

export function ExitFrameMode():Promise<main.ROI>;

export function ExportPDF(arg1:string):Promise<string>;

export function GetCapturedCount():Promise<number>;

export function GetDisplayData():Promise<Record<string, any>>;

export function GetMirrorData():Promise<Record<string, any>>;

export function GetSnipData():Promise<Record<string, any>>;

export function OpenFolder():Promise<void>;

export function Quit():Promise<void>;

export function SelectArea():Promise<string>;

export function SetROI(arg1:main.ROI):Promise<string>;

export function StartCapture():Promise<string>;

export function StopCapture():Promise<string>;
